// File generated by FlutterFire CLI.
// This is a template file. You need to run 'flutterfire configure' to generate the actual configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAfJ59BIQZfnSqhPvjKLlco9S6sgMiNv0',
    appId: '1:919018038056:web:placeholder',
    messagingSenderId: '919018038056',
    projectId: 'home-and-homies',
    authDomain: 'home-and-homies.firebaseapp.com',
    storageBucket: 'home-and-homies.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAfJ59BIQZfnSqhPvjKLlco9S6sgMiNv0',
    appId: '1:919018038056:android:5a7233d550af4ecc46e61d',
    messagingSenderId: '919018038056',
    projectId: 'home-and-homies',
    storageBucket: 'home-and-homies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfJ59BIQZfnSqhPvjKLlco9S6sgMiNv0',
    appId: '1:919018038056:ios:placeholder',
    messagingSenderId: '919018038056',
    projectId: 'home-and-homies',
    storageBucket: 'home-and-homies.firebasestorage.app',
    iosBundleId: 'com.example.task2FirestoreBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAfJ59BIQZfnSqhPvjKLlco9S6sgMiNv0',
    appId: '1:919018038056:ios:placeholder',
    messagingSenderId: '919018038056',
    projectId: 'home-and-homies',
    storageBucket: 'home-and-homies.firebasestorage.app',
    iosBundleId: 'com.example.task2FirestoreBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAfJ59BIQZfnSqhPvjKLlco9S6sgMiNv0',
    appId: '1:919018038056:web:placeholder',
    messagingSenderId: '919018038056',
    projectId: 'home-and-homies',
    authDomain: 'home-and-homies.firebaseapp.com',
    storageBucket: 'home-and-homies.firebasestorage.app',
  );
}
