// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4rIsy8r_bXLkvBJNaSfmB8O_cZ9NipKM',
    appId: '1:648364722603:android:bc2dcb3f3ecc91bd386aee',
    messagingSenderId: '648364722603',
    projectId: 'hackathon-5042e',
    storageBucket: 'hackathon-5042e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4rIsy8r_bXLkvBJNaSfmB8O_cZ9NipKM',
    appId: '1:648364722603:ios:bc2dcb3f3ecc91bd386aee',
    messagingSenderId: '648364722603',
    projectId: 'hackathon-5042e',
    storageBucket: 'hackathon-5042e.firebasestorage.app',
    iosBundleId: 'com.homies.apk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rIsy8r_bXLkvBJNaSfmB8O_cZ9NipKM',
    appId: '1:648364722603:web:bc2dcb3f3ecc91bd386aee',
    messagingSenderId: '648364722603',
    projectId: 'hackathon-5042e',
    authDomain: 'hackathon-5042e.firebaseapp.com',
    storageBucket: 'hackathon-5042e.firebasestorage.app',
    measurementId: 'G-PKCRFGXDM2',
  );
}
